LABEL Armbian
  LINUX /Image
  INITRD /uInitrd
  FDT /dtb/rockchip/rk3399-gea8319.dtb
  APPEND root=UUID=ffffab2f-dde3-45f1-88a6-69dfe2a62367 rootflags=compress=zstd:1 rw rootwait rootfstype=btrfs console=ttyS2,1500000 console=tty1 no_console_suspend consoleblank=0 fsck.fix=yes fsck.repair=yes net.ifnames=0 max_loop=128 bootsplash.bootfile=bootsplash.armbian
